// <auto-generated />
using System;
using Danske_TaxCalucationAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Danske_TaxCalucationAPI.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220315072851_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Danske_TaxCalucationAPI.Models.ManageRuleDTO", b =>
                {
                    b.Property<int>("RuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("PeriodId")
                        .HasColumnType("int");

                    b.Property<string>("RuleType")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RuleID");

                    b.ToTable("ManageRuleDTO");
                });

            modelBuilder.Entity("Danske_TaxCalucationAPI.Models.MunicipalityDTO", b =>
                {
                    b.Property<int>("MunicipalityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("MunicipalityName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RuleID")
                        .HasColumnType("int");

                    b.HasKey("MunicipalityID");

                    b.ToTable("MunicipalityDTO");
                });

            modelBuilder.Entity("Danske_TaxCalucationAPI.Models.PeriodDetailsDTO", b =>
                {
                    b.Property<int>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PeriodType")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RuleID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PeriodId");

                    b.ToTable("PeriodDetailsDTO");
                });

            //modelBuilder.Entity("Danske_TaxCalucationAPI.Models.CommonModel", b =>
            //{

            //    b.Property<string>("Municipality")
            //        .HasColumnType("nvarchar(20)");

            //    b.Property<DateTime>("Date")
            //            .HasColumnType("datetime2");

            //    b.Property<string>("TaxRule")
            //        .HasColumnType("nvarchar(20)");

            //    b.Property<decimal>("Result")
            //           .HasColumnType("decimal(18,2)");

            //    b.HasNoKey();

            //    b.ToTable("CommonModel");
            //});
#pragma warning restore 612, 618
        }
    }
}
